// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef pola_h
#define pola_h
#include <FL/Fl.H>
#include "widok.h"
#include "app.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Dial.H>
#include <FL/Fl_Button.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *okno1;
  Widok_t *Widok1;
  Fl_Counter *numer;
private:
  inline void cb_numer_i(Fl_Counter*, void*);
  static void cb_numer(Fl_Counter*, void*);
public:
  Fl_Check_Button *wlacznik;
private:
  inline void cb_wlacznik_i(Fl_Check_Button*, void*);
  static void cb_wlacznik(Fl_Check_Button*, void*);
public:
  Fl_Value_Input *wsp_x;
private:
  inline void cb_wsp_x_i(Fl_Value_Input*, void*);
  static void cb_wsp_x(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *wsp_y;
private:
  inline void cb_wsp_y_i(Fl_Value_Input*, void*);
  static void cb_wsp_y(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *ladunek;
private:
  inline void cb_ladunek_i(Fl_Value_Input*, void*);
  static void cb_ladunek(Fl_Value_Input*, void*);
  inline void cb_G_i(Fl_Dial*, void*);
  static void cb_G(Fl_Dial*, void*);
  inline void cb_Rysuj_i(Fl_Button*, void*);
  static void cb_Rysuj(Fl_Button*, void*);
  inline void cb_Powi_i(Fl_Value_Input*, void*);
  static void cb_Powi(Fl_Value_Input*, void*);
};
#endif
