// generated by Fast Light User Interface Designer (fluid) version 1.0105

#include "pola.h"

inline void UserInterface::cb_numer_i(Fl_Counter*, void*) {
  unsigned n = unsigned(numer->value() - 1);
wlacznik->value(App1.Zrodla[n].wlaczone());
wsp_x->value(App1.Zrodla[n].x);
wsp_y->value(App1.Zrodla[n].y);
ladunek->value(App1.Zrodla[n].q);
}
void UserInterface::cb_numer(Fl_Counter* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_numer_i(o,v);
}

inline void UserInterface::cb_wlacznik_i(Fl_Check_Button*, void*) {
  unsigned n = unsigned(numer->value() - 1);
if (App1.Zrodla[n].wlaczone())
   App1.Zrodla[n].wylacz();
else
   App1.Zrodla[n].wlacz();
Widok1->redraw();
}
void UserInterface::cb_wlacznik(Fl_Check_Button* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_wlacznik_i(o,v);
}

inline void UserInterface::cb_wsp_x_i(Fl_Value_Input* o, void*) {
  App1.Zrodla[unsigned(numer->value() - 1)].x = o->value();
Widok1->redraw();
}
void UserInterface::cb_wsp_x(Fl_Value_Input* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_wsp_x_i(o,v);
}

inline void UserInterface::cb_wsp_y_i(Fl_Value_Input* o, void*) {
  App1.Zrodla[unsigned(numer->value() - 1)].y = o->value();
Widok1->redraw();
}
void UserInterface::cb_wsp_y(Fl_Value_Input* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_wsp_y_i(o,v);
}

inline void UserInterface::cb_ladunek_i(Fl_Value_Input* o, void*) {
  App1.Zrodla[unsigned(numer->value() - 1)].q = o->value();
Widok1->redraw();
}
void UserInterface::cb_ladunek(Fl_Value_Input* o, void* v) {
  ((UserInterface*)(o->parent()->parent()->user_data()))->cb_ladunek_i(o,v);
}

inline void UserInterface::cb_G_i(Fl_Dial* o, void*) {
  App1.gestosc = o->maximum() - o->value() + 0.05;
Widok1->redraw();
}
void UserInterface::cb_G(Fl_Dial* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_G_i(o,v);
}

inline void UserInterface::cb_Rysuj_i(Fl_Button*, void*) {
  Widok1->redraw();
}
void UserInterface::cb_Rysuj(Fl_Button* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Rysuj_i(o,v);
}

inline void UserInterface::cb_Powi_i(Fl_Value_Input* o, void*) {
  App1.skala = o->value();
Widok1->redraw();
}
void UserInterface::cb_Powi(Fl_Value_Input* o, void* v) {
  ((UserInterface*)(o->parent()->user_data()))->cb_Powi_i(o,v);
}

UserInterface::UserInterface() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = okno1 = new Fl_Double_Window(800, 600, "Pola fizyczne");
    w = o;
    o->user_data((void*)(this));
    { Widok_t* o = Widok1 = new Widok_t(0, 0, 600, 600);
      o->box(FL_THIN_DOWN_FRAME);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CLIP);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Counter* o = numer = new Fl_Counter(611, 40, 182, 27, "Number \274r\363""d\263""a:");
      o->minimum(1);
      o->maximum(4);
      o->step(1);
      o->value(1);
      o->callback((Fl_Callback*)cb_numer);
      o->align(FL_ALIGN_TOP);
      o->labelfont(PL_Font);
    }
    { Fl_Group* o = new Fl_Group(611, 91, 182, 205);
      o->box(FL_THIN_DOWN_FRAME);
      { Fl_Check_Button* o = wlacznik = new Fl_Check_Button(630, 96, 141, 25, "\254r\363""d\263o w\263\261""czone");
        o->down_box(FL_DOWN_BOX);
        o->callback((Fl_Callback*)cb_wlacznik);
        o->labelfont(PL_Font);
      }
      { Fl_Value_Input* o = wsp_x = new Fl_Value_Input(666, 153, 69, 22, "Wsp\363\263rz\352""dna X:");
        o->minimum(-10);
        o->maximum(10);
        o->step(0.5);
        o->callback((Fl_Callback*)cb_wsp_x);
        o->align(FL_ALIGN_TOP);
        o->labelfont(PL_Font);
      }
      { Fl_Value_Input* o = wsp_y = new Fl_Value_Input(666, 207, 69, 22, "Wsp\363\263rz\352""dna Y:");
        o->minimum(-10);
        o->maximum(10);
        o->step(0.5);
        o->callback((Fl_Callback*)cb_wsp_y);
        o->align(FL_ALIGN_TOP);
        o->labelfont(PL_Font);
      }
      { Fl_Value_Input* o = ladunek = new Fl_Value_Input(666, 261, 69, 22, "\243""adunek \274r\363""d\263""a:");
        o->minimum(-10);
        o->maximum(10);
        o->step(0.5);
        o->callback((Fl_Callback*)cb_ladunek);
        o->align(FL_ALIGN_TOP);
        o->labelfont(PL_Font);
      }
      o->end();
    }
    { Fl_Dial* o = new Fl_Dial(672, 379, 60, 60, "G\352sto\266\346 linii pola:");
      o->type(1);
      o->color((Fl_Color)53);
      o->selection_color((Fl_Color)1);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->minimum(0.1);
      o->maximum(3);
      o->step(0.1);
      o->value(0.7);
      o->callback((Fl_Callback*)cb_G);
      o->align(FL_ALIGN_TOP);
      o->labelfont(PL_Font);
      o->value(3 - App1.gestosc);
    }
    { Fl_Button* o = new Fl_Button(608, 474, 186, 46, "Rysuj linie pola");
      o->callback((Fl_Callback*)cb_Rysuj);
      o->labelfont(PL_Font);
    }
    { Fl_Value_Input* o = new Fl_Value_Input(725, 320, 69, 22, "Powi\352kszenie:");
      o->minimum(0.1);
      o->maximum(100);
      o->step(1);
      o->value(10);
      o->callback((Fl_Callback*)cb_Powi);
      o->labelfont(PL_Font);
      o->value(App1.skala);
    }
    o->end();
  }
  numer->maximum(MAX_ZRODEL);
okno1->show();
  okno1->show();
}
